### ISSUE TITLE
Revisit p2p hosting of ournetworks.ca over IPFS+Dat

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#31]
Picking up the thread from https://github.com/ournetworks/2018/issues/12, updated todos below:

---

- [x] Review status from last year (hosted over Dat https://github.com/ournetworks/ournetworks.ca/pull/20, using [`garry` Hashbase](https://hashbase.io/garry/ournetworks) to peer, running [Homebase](https://github.com/beakerbrowser/homebase) <<- still working?) 
- [x] Set up `ournetworks` hashbase
- [x] Decision of automating publishing flow 
  - [x] IPFS publishing workflow
  - [x] Dat syncing workflow
- [ ] Add info about p2p versions to website @garrying
  - [x] Dat -> https://github.com/ournetworks/ournetworks.ca/pull/130
  - [ ] IPFS   
- [ ] Do we want an ipfs node on server?

**Comment by garrying** [comment]
re homebase: The process (`pm2`) is still running and working as far as I can tell

re IPFS: A few initial thought:
- I think a refactoring is needed so that get relative links working because of the way urls are defined through gateways
- Seems like [DNSLink](https://docs.ipfs.io/guides/concepts/dnslink/) is still a preferred method in point to the correct hash
- There could be something here: https://github.com/AuHau/ipfs-publish

IPFS + Dat loose thoughts:
- Maybe CI workflow(s) to do both?
- Moving things into Docker probably makes sense for reproducibility and other cases
- Maybe use GitHub's webhooks to trigger build/deploy

**Comment by dcwalk** [comment]
Thinking about reconciling jekyll link resolution and IPFS...

- look at current docker image
- find old regex thing? (@dcwalk swears it exists)
- switch to DO for domain management (api!)
- how do we deal with mail forwarders? (@dcwalk thinks MayFirst could do it!)

**Comment by dcwalk** [comment]
Oh here was an IPFS camp sesh on it with more helpful links: https://github.com/ipfs/camp/blob/master/DEEP_DIVES/13-ipfs-for-websites-static-dynamic-search-etc.md

**Comment by dcwalk** [comment]
ping @garrying here is our todo on adding mention of Dat to the website!

**Comment by dcwalk** [comment]
https://devpost.com/software/decentralify

> What it does
>
> Takes a GitHub repo with an app (VuePress, Hugo, Gatsby, etc), builds it on iExec, uploads the assets to IPFS and provides a simple domain via FISSION.
How we built it
> 
> We took the Netlify build-image and added functionality to be compatible with iExec and ipfs-deploy.
